version: "3.8"
services:
  reviewer:
    image: postgres:15.1
    container_name: task-reviewer-db
    environment:
      POSTGRES_DB: task-reviewer-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U postgres -d check
      interval: 10s
      timeout: 3s
