spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/task-reviewer-db}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  application:
    name: reviewer
  liquibase:
    default-schema: public
    enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
app:
  branch: ${BRANCH:2}
  tasks-path: ${TASKS_PATH:classpath:csv/received/core.read.from.file}
